# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cd36af055c88ce9c06445e58c8851f023e434a07421a094cd38d1a3e888418fe54c4c0b10421880642d47cd7b3db5f360d34fb3ba5d36e94027e54b715ebaa6

test:
  secret_key_base: 63f6fd71d4cbd5bfb434b3d43714290a87d93b76e3541b043521903a24a23bd8bcb5f5f5986f8fdddc9c9cc34488491f95002f394088d9286f6628312c624d7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
